#!/bin/sh
killall xcape >/dev/null 2>/dev/null
setxkbmap dvorak -option "compose:102"
for file in $@; do
    echo $file
    xmodmap $1
done
xmodmap ~/.keymaps/swedish-aoe
# xmodmap -e 'clear Control'
# xmodmap -e 'keycode 23 = Control_R'
# xmodmap -e 'add Control = Control_R'
# xmodmap -e 'keycode 254 = Tab Tab'
# xmodmap -e 'keycode 49 = grave asciitilde Tab ISO_Left_Tab'
xmodmap -e 'keycode 253 = Delete'
if [[ $(lsusb | grep -i kinesis) ]]; then
    xcape -e 'Alt_L=Delete;Control_L=BackSpace'
else
    xcape -e 'Control_R=Tab;Super_L=Delete;Alt_L=BackSpace;Mode_switch=Return'
fi
xset r rate 150
xset b off
