#!/bin/sh
killall xcape >/dev/null
setxkbmap dvorak -option "compose:102"
for file in $@; do
    echo $file
    xmodmap $1
done
xmodmap ~/.keymaps/swedish-aoe
xmodmap -e 'clear Control'
xmodmap -e 'keysym Tab = Control_R'
xmodmap -e 'add Control = Control_R'
xmodmap -e 'keycode 254 = Tab Tab'
if [[ $(lsusb | grep -i kinesis) ]]; then
    xcape -e 'Control_R=Tab;Alt_L=Delete'
else
    xcape -e 'Control_R=Tab;Super_L=Delete;Alt_L=BackSpace;Mode_switch=Return'
fi
xset r rate 150
xset b off
