#!/bin/bash

# sudo modprobe iwldvm

setxkbmap dvorak -option compose:102
xmodmap ~/.keymaps/fix-gunka-advantage
xmodmap ~/.keymaps/swapcapsesc
xmodmap ~/.keymaps/swedish-aoe
xset r rate 150
xset b off
xmodmap -pm
sudo dhcpcd eno1

xrandr --output LVDS1 --off --output VGA1 --auto
# sleep 0.1
# sudo netcfg eduroam &
ssh-add
