#!/bin/bash

# sudo modprobe iwldvm

setxkbmap dvorak -option compose:102
xmodmap ~/.keymaps/fix-gunka-advantage
xmodmap ~/.keymaps/swapcapsesc
# xmodmap ~/.keymaps/swapcapsctrl
# add Control=Control_L
# xmodmap -e 'keycode 999 = Escape'
# killall xcape
# xcape -e 'Control_L=Escape'
xmodmap ~/.keymaps/swedish-aoe
xset r rate 150
xset b off
xmodmap -pm
#ssh-add
#sudo dhcpcd eno1
xrandr --output LVDS-1 --off --output DP-1 --auto 2> /dev/null > /dev/null
xrandr --output LVDS-2 --off --output DP-2 --auto 2> /dev/null > /dev/null
xrandr --output LVDS1  --off --output VGA1 --auto 2> /dev/null > /dev/null
xrandr --output LVDS2  --off --output VGA2 --auto 2> /dev/null > /dev/null
